# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TESTS

on:
  push:
    #TODO change it when release 
    branches: [ "feature/v2" ]
  pull_request:
    #TODO change it when release 
    branches: [ "feature/v2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
          insecure_ignore_fingerprint: true
#       - name: "checkout repo"
#         uses: actions/checkout@v3
#         with:
#           ref: "feature/v2"
#       - name: "nodejs install"
#         uses: actions/setup-node@v3
#         with:
#            node-version: ${{ matrix.node-version }}
#       - name: "dependecy install"
#         uses: borales/actions-yarn@v3.0.0
#         with: 
#           cmd: intsall --frozen-lockfile    
#       - name: "run tests"
#         uses: borales/actions-yarn@v3.0.0
#         with: 
#           cmd: test:unit
